#!/bin/sh
#This script is for copying Aediles_Thrall.pl accross the starter zones
#since it seems to work better i f script resides with him.
echo ../akanon ../bazaar ../cabeast ../cabwest ../erudnint ../felwithea ../felwitheb ../freporte ../freportw ../gfaydark ../grobb ../gukta ../halas ../kaladima ../kaladimb ../kerraridge ../neriaka ../neriakc ../oggok ../paineel ../poknowledge ../qeynos ../qeynos2 ../qrg ../rathemtn ../rivervale ../shadeweaver ../sharvahl ../swampofnohope ../tutorialb | xargs -n 1 cp -v Aediles_Thrall.pl
