<?

$eqzones = array(
  array('expansion' => 1, 'zone' => 'airplane'),
  array('expansion' => 1, 'zone' => 'akanon'),
  array('expansion' => 1, 'zone' => 'arena'),
  array('expansion' => 1, 'zone' => 'befallen'),
  array('expansion' => 1, 'zone' => 'beholder'),
  array('expansion' => 1, 'zone' => 'blackburrow'),
  array('expansion' => 1, 'zone' => 'butcher'),
  array('expansion' => 1, 'zone' => 'cauldron'),
  array('expansion' => 1, 'zone' => 'cazicthule'),
  array('expansion' => 1, 'zone' => 'commons'),
  array('expansion' => 1, 'zone' => 'crushbone'),
  array('expansion' => 1, 'zone' => 'cshome'),
  array('expansion' => 1, 'zone' => 'eastkarana'),
  array('expansion' => 1, 'zone' => 'ecommons'),
  array('expansion' => 1, 'zone' => 'erudnext'),
  array('expansion' => 1, 'zone' => 'erudnint'),
  array('expansion' => 1, 'zone' => 'erudsxing'),
  array('expansion' => 1, 'zone' => 'everfrost'),
  array('expansion' => 1, 'zone' => 'fearplane'),
  array('expansion' => 1, 'zone' => 'feerrott'),
  array('expansion' => 1, 'zone' => 'felwithea'),
  array('expansion' => 1, 'zone' => 'felwitheb'),
  array('expansion' => 1, 'zone' => 'freporte'),
  array('expansion' => 1, 'zone' => 'freportn'),
  array('expansion' => 1, 'zone' => 'freportw'),
  array('expansion' => 1, 'zone' => 'gfaydark'),
  array('expansion' => 1, 'zone' => 'gukbottom'),
  array('expansion' => 1, 'zone' => 'grobb'),
  array('expansion' => 1, 'zone' => 'gukta'),
  array('expansion' => 1, 'zone' => 'guktop'),
  array('expansion' => 1, 'zone' => 'halas'),
  array('expansion' => 1, 'zone' => 'hateplane'),
  array('expansion' => 1, 'zone' => 'highkeep'),
  array('expansion' => 1, 'zone' => 'highpass'),
  array('expansion' => 1, 'zone' => 'hole'),
  array('expansion' => 1, 'zone' => 'innothule'),
  array('expansion' => 1, 'zone' => 'kaladima'),
  array('expansion' => 1, 'zone' => 'kaladimb'),
  array('expansion' => 1, 'zone' => 'kedge'),
  array('expansion' => 1, 'zone' => 'kerraridge'),
  array('expansion' => 1, 'zone' => 'kithicor'),
  array('expansion' => 1, 'zone' => 'lakerathe'),
  array('expansion' => 1, 'zone' => 'lavastorm'),
  array('expansion' => 1, 'zone' => 'lfaydark'),
  array('expansion' => 1, 'zone' => 'mistmoore'),
  array('expansion' => 1, 'zone' => 'misty'),
  array('expansion' => 1, 'zone' => 'najena'),
  array('expansion' => 1, 'zone' => 'nektulos'),
  array('expansion' => 1, 'zone' => 'neriaka'),
  array('expansion' => 1, 'zone' => 'neriakb'),
  array('expansion' => 1, 'zone' => 'neriakc'),
  array('expansion' => 1, 'zone' => 'northkarana'),
  array('expansion' => 1, 'zone' => 'nro'),
  array('expansion' => 1, 'zone' => 'oasis'),
  array('expansion' => 1, 'zone' => 'oggok'),
  array('expansion' => 1, 'zone' => 'oot'),
  array('expansion' => 1, 'zone' => 'paineel'),
  array('expansion' => 1, 'zone' => 'paw'),
  array('expansion' => 1, 'zone' => 'permafrost'),
  array('expansion' => 1, 'zone' => 'qcat'),
  array('expansion' => 1, 'zone' => 'qey2hh1'),
  array('expansion' => 1, 'zone' => 'qeynos'),
  array('expansion' => 1, 'zone' => 'qeynos2'),
  array('expansion' => 1, 'zone' => 'qeytoqrg'),
  array('expansion' => 1, 'zone' => 'qrg'),
  array('expansion' => 1, 'zone' => 'rathemtn'),
  array('expansion' => 1, 'zone' => 'rivervale'),
  array('expansion' => 1, 'zone' => 'runnyeye'),
  array('expansion' => 1, 'zone' => 'soldunga'),
  array('expansion' => 1, 'zone' => 'soldungb'),
  array('expansion' => 1, 'zone' => 'soltemple'),
  array('expansion' => 1, 'zone' => 'southkarana'),
  array('expansion' => 1, 'zone' => 'sro'),
  array('expansion' => 1, 'zone' => 'steamfont'),
  array('expansion' => 1, 'zone' => 'stonebrunt'),
  array('expansion' => 1, 'zone' => 'tox'),
  array('expansion' => 1, 'zone' => 'unrest'),


  array('expansion' => 2, 'zone' => 'burningwood'),
  array('expansion' => 2, 'zone' => 'cabeast'),
  array('expansion' => 2, 'zone' => 'cabwest'),
  array('expansion' => 2, 'zone' => 'charasis'),
  array('expansion' => 2, 'zone' => 'chardok'),
  array('expansion' => 2, 'zone' => 'citymist'),
  array('expansion' => 2, 'zone' => 'dalnir'),
  array('expansion' => 2, 'zone' => 'dreadlands'),
  array('expansion' => 2, 'zone' => 'droga'),
  array('expansion' => 2, 'zone' => 'emeraldjungle'),
  array('expansion' => 2, 'zone' => 'fieldofbone'),
  array('expansion' => 2, 'zone' => 'firiona'),
  array('expansion' => 2, 'zone' => 'frontiermtns'),
  array('expansion' => 2, 'zone' => 'kaesora'),
  array('expansion' => 2, 'zone' => 'karnor'),
  array('expansion' => 2, 'zone' => 'kurn'),
  array('expansion' => 2, 'zone' => 'lakeofillomen'),
  array('expansion' => 2, 'zone' => 'nurga'),
  array('expansion' => 2, 'zone' => 'overthere'),
  array('expansion' => 2, 'zone' => 'sebilis'),
  array('expansion' => 2, 'zone' => 'skyfire'),
  array('expansion' => 2, 'zone' => 'swampofnohope'),
  array('expansion' => 2, 'zone' => 'timorous'),
  array('expansion' => 2, 'zone' => 'trakanon'),
  array('expansion' => 2, 'zone' => 'veeshan'),
  array('expansion' => 2, 'zone' => 'veksar'),
  array('expansion' => 2, 'zone' => 'warrens'),
  array('expansion' => 2, 'zone' => 'warslikswood'),

  array('expansion' => 6, 'zone' => 'nadox'),
  array('expansion' => 6, 'zone' => 'tutorialb'),
  array('expansion' => 6, 'zone' => 'dulak'),
  array('expansion' => 6, 'zone' => 'gunthak'),
  array('expansion' => 6, 'zone' => 'hatesfury'),
  array('expansion' => 6, 'zone' => 'torgiran'),
);

$zones = array();
foreach ($eqzones as $zone) {
  if ($zone['expansion'] <= $expansion_limit) {
    $zones[] = $zone['zone'];
  }
}
sort ($zones);

?>