#!/bin/sh
#This script is for copying #Countess_Zellia.pl accross the starter zones
echo ../rivervale ../nektulos ../everfrost ../tox ../butcher ../fieldofbone ../felwithea ../freporte ../freportw ../gfaydark  ../oggok ../qeynos ../qrg ../shadeweaver ../swampofnohope ../tutorialb ../akanon | xargs -n 1 ln -s /home/angelox/eqemu/server/GitHub_Repo/quests/templates/'#Countess_Zellia.pl' '#Countess_Zellia.pl'
