#!/bin/sh
#This script is for copying Ranger_Band.pl accross the starter zones
echo ../rivervale ../nektulos ../everfrost ../tox ../butcher ../fieldofbone ../felwithea ../freporte ../freportw ../gfaydark  ../oggok ../qeynos ../qrg ../shadeweaver ../swampofnohope ../tutorialb ../paineel | xargs -n 1 ln -s /home/angelox/eqemu/server/GitHub_Repo/quests/templates/'Ranger_Band.pl' 'Ranger_Band.pl'
