#!/bin/sh
#This script is for copying player.pl accross the starter zones
#since it seems to work better i f script resides in the zone.
echo ../akanon ../bazaar ../cabeast ../cabwest ../erudnint ../felwithea ../felwitheb ../freporte ../freportw ../gfaydark ../grobb ../gukta ../halas ../kaladima ../kaladimb ../kerraridge ../neriaka ../neriakc ../oggok ../paineel ../poknowledge ../qeynos ../qeynos2 ../qrg ../rathemtn ../rivervale ../shadeweaver ../sharvahl ../swampofnohope ../tutorialb ../misty ../nektulos ../everfrost ../tox ../butcher ../qeytoqrg ../innothule ../feerrott ../steamfont ../fieldofbone  ../kithicor ../droga ../nurga ../cazicthule | xargs -n 1 cp -v player.pl
