#!/bin/bash
emuPath=/eqemu/source/EQEmuLoginServer/
cd $emuPath
echo Stopping any other mounted Login Servers...
killall EQEmuLoginServer &
sleep 3
echo Done.
sleep 3
echo Starting Public Login Server...
./EQEmuLoginServer &
sleep 5
echo Done.
