#!/bin/sh
#This script is for copying #Champion_Darkwater.pl accross the starter zones
echo ../rivervale ../nektulos ../everfrost ../tox ../butcher ../felwithea ../freporte ../gfaydark  ../oggok ../qeynos ../qeynos2 ../cabeast ../cabwest ../kerraridge ../akanon ../qrg ../shadeweaver ../swampofnohope ../paineel | xargs -n 1 cp -v '#Champion_Darkwater.pl'
