DELETE QUICK FROM aa_actions;
DELETE QUICK FROM aa_swarmpets;
DELETE QUICK FROM aa_timers;
DELETE QUICK FROM activities;
DELETE QUICK FROM altadv_vars;
DELETE QUICK FROM books;
DELETE QUICK FROM class_skill;
DELETE QUICK FROM db_version;
DELETE QUICK FROM doors;
DELETE QUICK FROM faction_list;
DELETE QUICK FROM fear_hints;
DELETE QUICK FROM fishing;
DELETE QUICK FROM forage;
DELETE QUICK FROM goallists;
DELETE QUICK FROM grid;
DELETE QUICK FROM grid_entries;
DELETE QUICK FROM ground_spawns;
DELETE QUICK FROM horses;
DELETE QUICK FROM launcher;
DELETE QUICK FROM lootdrop;
DELETE QUICK FROM lootdrop_entries;
DELETE QUICK FROM loottable;
DELETE QUICK FROM loottable_entries;
DELETE QUICK FROM merchantlist;
DELETE QUICK FROM merchantsets;
DELETE QUICK FROM npc_faction;
DELETE QUICK FROM npc_faction_entries;
DELETE QUICK FROM npc_spells;
DELETE QUICK FROM npc_spells_entries;
DELETE QUICK FROM object;
DELETE QUICK FROM pets;
DELETE QUICK FROM respawn_times;
DELETE QUICK FROM rule_sets;
DELETE QUICK FROM rule_values;
DELETE QUICK FROM saylink;
DELETE QUICK FROM skill_caps;
DELETE QUICK FROM spawn2;
DELETE QUICK FROM spawn_conditions;
DELETE QUICK FROM spawn_events;
DELETE QUICK FROM spawnentry;
DELETE QUICK FROM spawngroup;
DELETE QUICK FROM spells;
DELETE QUICK FROM spells_new;
DELETE QUICK FROM start_zones;
DELETE QUICK FROM starting_items;
DELETE QUICK FROM tasks;
DELETE QUICK FROM tasksets;
DELETE QUICK FROM tradeskill_recipe;
DELETE QUICK FROM tradeskill_recipe_entries;
DELETE QUICK FROM traps;
DELETE QUICK FROM tribute_levels;
DELETE QUICK FROM tributes;
DELETE QUICK FROM zone;
DELETE QUICK FROM zone_points;
DELETE QUICK FROM zone_server;
DELETE QUICK FROM zone_state_dump;
DELETE QUICK FROM zoneserver_auth;
DELETE QUICK FROM npc_types WHERE isbot!=1;
DELETE QUICK FROM items;
DELETE QUICK FROM aa_effects;
DELETE QUICK FROM core_version;
DELETE QUICK FROM damageshieldtypes;
DELETE QUICK FROM object_contents;
DELETE QUICK FROM proximities;

ALTER TABLE `ax_classic`.`aa_actions` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`aa_swarmpets` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`aa_timers` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`activities` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`altadv_vars` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`books` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`class_skill` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`db_version` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`doors` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`faction_list` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`fear_hints` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`fishing` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`forage` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`goallists` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`grid` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`grid_entries` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`ground_spawns` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`horses` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`launcher` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`lootdrop` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`lootdrop_entries` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`loottable` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`loottable_entries` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`merchantlist` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`merchantsets` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`npc_faction` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`npc_faction_entries` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`npc_spells` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`npc_spells_entries` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`object` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`pets` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`respawn_times` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`rule_sets` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`rule_values` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`saylink` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`skill_caps` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`spawn2` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`spawn_conditions` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`spawn_events` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`spawnentry` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`spawngroup` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`spells` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`spells_new` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`start_zones` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`starting_items` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`tasks` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`tasksets` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`tradeskill_recipe` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`tradeskill_recipe_entries` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`traps` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`tribute_levels` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`tributes` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`zone` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`zone_points` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`zone_server` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`zone_state_dump` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`zoneserver_auth` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`npc_types` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`items` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`aa_effects` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`core_version` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`damageshieldtypes` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`object_contents` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`proximities` AUTO_INCREMENT = 1;

