DELETE QUICK FROM account;
DELETE QUICK FROM mail;
DELETE QUICK FROM character_;
DELETE QUICK FROM character_backup;
DELETE QUICK FROM character_activities;
DELETE QUICK FROM character_enabledtasks;
DELETE QUICK FROM character_tasks;
DELETE QUICK FROM chatchannels;
DELETE QUICK FROM completed_tasks;
DELETE QUICK FROM buyer;
DELETE QUICK FROM player_titlesets;
DELETE QUICK FROM eventlog;
DELETE QUICK FROM faction_values;
DELETE QUICK FROM graveyard;
DELETE QUICK FROM guild_members;
DELETE QUICK FROM guild_ranks;
DELETE QUICK FROM guild_relations;
DELETE QUICK FROM guilds;
DELETE QUICK FROM inventory;
DELETE QUICK FROM keyring;
DELETE QUICK FROM merchantlist_temp;
DELETE QUICK FROM peq_admin;
DELETE QUICK FROM petitions;
DELETE QUICK FROM player_corpses;
DELETE QUICK FROM player_corpses_backup;
DELETE QUICK FROM sharedbank;
DELETE QUICK FROM zone_flags;
DELETE QUICK FROM botinventory;
DELETE QUICK FROM botgroups;
DELETE QUICK FROM botgroups_b;
DELETE QUICK FROM botgroups_c;
DELETE QUICK FROM botbank;
DELETE QUICK FROM botleader;
DELETE QUICK FROM botsowners;
DELETE QUICK FROM quest_globals;
DELETE QUICK FROM account_ip;
DELETE QUICK FROM banned_ips;
DELETE QUICK FROM bugs;
DELETE QUICK FROM commands;
DELETE QUICK FROM hackers;
DELETE QUICK FROM qed_admin;
DELETE QUICK FROM qed_quests;
DELETE QUICK FROM qed_zone;
DELETE QUICK FROM timers;
DELETE QUICK FROM titles;
DELETE QUICK FROM variables;

ALTER TABLE `ax_classic`.`botinventory` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`account_ip` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`banned_ips` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`bugs` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`commands` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`hackers` AUTO_INCREMENT = 1; 
ALTER TABLE `ax_classic`.`qed_admin` AUTO_INCREMENT = 1; 
ALTER TABLE `ax_classic`.`qed_quests` AUTO_INCREMENT = 1; 
ALTER TABLE `ax_classic`.`qed_zone` AUTO_INCREMENT = 1; 
ALTER TABLE `ax_classic`.`timers` AUTO_INCREMENT = 1; 
ALTER TABLE `ax_classic`.`variables` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`quest_globals` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`player_titlesets` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`account` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`buyer` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`character_` AUTO_INCREMENT = 1; 
ALTER TABLE `ax_classic`.`character_backup` AUTO_INCREMENT = 1; 
ALTER TABLE `ax_classic`.`character_activities` AUTO_INCREMENT = 1; 
ALTER TABLE `ax_classic`.`eventlog` AUTO_INCREMENT = 1; 
ALTER TABLE `ax_classic`.`faction_values` AUTO_INCREMENT = 1; 
ALTER TABLE `ax_classic`.`graveyard` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`guild_members` AUTO_INCREMENT = 1; 
ALTER TABLE `ax_classic`.`guild_ranks` AUTO_INCREMENT = 1; 
ALTER TABLE `ax_classic`.`guild_relations` AUTO_INCREMENT = 1; 
ALTER TABLE `ax_classic`.`guilds` AUTO_INCREMENT = 1; 
ALTER TABLE `ax_classic`.`inventory` AUTO_INCREMENT = 1; 
ALTER TABLE `ax_classic`.`keyring` AUTO_INCREMENT = 1;
ALTER TABLE `ax_classic`.`merchantlist_temp` AUTO_INCREMENT = 1; 
ALTER TABLE `ax_classic`.`peq_admin` AUTO_INCREMENT = 1; 
ALTER TABLE `ax_classic`.`petitions` AUTO_INCREMENT = 1; 
ALTER TABLE `ax_classic`.`player_corpses` AUTO_INCREMENT = 1; 
ALTER TABLE `ax_classic`.`player_corpses_backup` AUTO_INCREMENT = 1; 
ALTER TABLE `ax_classic`.`sharedbank` AUTO_INCREMENT = 1; 
ALTER TABLE `ax_classic`.`zone_flags` AUTO_INCREMENT = 1; 
ALTER TABLE `ax_classic`.`botinventory` AUTO_INCREMENT = 1; 
ALTER TABLE `ax_classic`.`botleader` AUTO_INCREMENT = 1; 
ALTER TABLE `ax_classic`.`botsowners` AUTO_INCREMENT = 1;
DELETE FROM npc_types where isbot=1;
ALTER TABLE `ax_classic`.`npc_types` AUTO_INCREMENT = 1; 

