
all: cleanipc
	
cleanipc: cleanipc.cpp
	g++ cleanipc.cpp -o cleanipc

# spell_explorer: spell_explorer.cpp
	g++ -g spell_explorer.cpp -o spell_explorer

clean:
	rm -f cleanipc
	rm -f spell_explorer

